name: Lab

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      DEPLOY_URL: "https://douglasangeli.github.io/${github.repository_name}"
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
        
      - name: Obter numero da tag mais recente
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - uses: jungwinter/split@v1
        name: Splitar nome da tag        
        id: split
        with:
            separator: '-'
            msg: '${{ steps.previoustag.outputs.tag }}'
      
      - uses: AsasInnab/regex-action@v1
        name: Verifica se o nome da tag possui SemVer no primeiro trecho        
        with:
            regex_pattern: '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$'
            regex_flags: 'gim'
            search_string: '${{ steps.split.outputs._0 }}'
      
      - name: Finaliza a action se o nome da tag nao possui SemVer
        if: ${{ steps.regex_versao.outputs.first_match }}
        uses: actions/github-script@v3
        with:
          script: core.setFailed('Validacao da versao do projeto falhou')

      - uses: jossef/action-set-json-field@v1
        name: Atualizar Package json        
        with:
            file: ./package.json
            field: version
            value: '${{ steps.split.outputs._0 }}'
            
      - uses: sarisia/actions-status-discord@v1
        name: Send success message
        if: success()      
        with:        
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          username: GitHub Actions
          title: "Deploy finalizado com sucesso"
          description: |
              :truck: Build da versão ${{ steps.previoustag.outputs.tag }} finalizado com sucesso.
              Acesso em: [Exemplos-Angular-Material](${{ env.DEPLOY_URL }})
              Infos da Action: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>    
              
      - uses: sarisia/actions-status-discord@v1
        name: Send failure message
        if: failure()      
        with:        
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          username: GitHub Actions
          title: "Falha no Deploy"
          description: |
              Build da versão ${{ steps.previoustag.outputs.tag }} finalizado com erro.
              Acesso em: [Exemplos-Angular-Material](${{ env.DEPLOY_URL }})
              Infos da Action: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>  
